/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pbo2.uas.f;

/**
 *
 * @author Administrator
 */
public class ProjekPenjualanSederhana extends javax.swing.JFrame {

    /**
     * Creates new form ProjekPenjualanSederhana
     */
    public ProjekPenjualanSederhana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtketerangan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmkodekonsumen = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtnama1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cmbkodebarang = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtnamabarang = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txthargabarang = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtsatuan = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtjumlahbeli = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtdiskon = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtuangbayar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtuangkembalian = new javax.swing.JTextField();
        btnprosesdiskon = new javax.swing.JButton();
        btnprosestotal = new javax.swing.JButton();
        btnuangbayar = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btnex = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Konsumen :");

        jLabel2.setText("Kode Konsumen :");

        cmkodekonsumen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "KS001", "KS002", "KS003", " " }));
        cmkodekonsumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmkodekonsumenActionPerformed(evt);
            }
        });

        jLabel3.setText("Keterangan :");

        jLabel4.setText("Kode Barang :");

        cmbkodebarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "B001", "B002", "B003", "B004", "B005" }));
        cmbkodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkodebarangActionPerformed(evt);
            }
        });

        jLabel5.setText("Nama Barang :");

        jLabel6.setText("Harga Barang :");

        jLabel7.setText("Satuan :");

        jLabel8.setText("Jumlah Beli :");

        txtjumlahbeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjumlahbeliActionPerformed(evt);
            }
        });

        jLabel9.setText("Diskon :");

        jLabel10.setText("Total Harga :");

        jLabel11.setText("Uang Bayar :");

        jLabel12.setText("Uang Kembalian :");

        btnprosesdiskon.setText("Proses Diskon");
        btnprosesdiskon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosesdiskonActionPerformed(evt);
            }
        });

        btnprosestotal.setText("Proses Total");
        btnprosestotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprosestotalActionPerformed(evt);
            }
        });

        btnuangbayar.setText("Proses Uang Bayar");
        btnuangbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuangbayarActionPerformed(evt);
            }
        });

        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btnex.setText("X");
        btnex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtjumlahbeli)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtnama1)
                                                .addComponent(cmkodekonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cmbkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txthargabarang)
                                                .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnprosesdiskon))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnprosestotal, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 39, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(bthapus))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnuangbayar)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtuangbayar)
                                    .addComponent(txtuangkembalian)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnex)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnex)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmkodekonsumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtketerangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnamabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthargabarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtsatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(txtjumlahbeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtdiskon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnprosesdiskon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bthapus)
                            .addComponent(btnuangbayar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnprosestotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtuangbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtuangkembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmkodekonsumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmkodekonsumenActionPerformed
        // TODO add your handling code here:
        String kodeks, keterangan ;
        
        kodeks = String.valueOf(cmkodekonsumen.getSelectedItem());
        
        if (kodeks.equals("KS001")){
            keterangan = "Members";
        }else
            if (kodeks.equals("KS002")){
            keterangan = " Non Members";
        }else
                if (kodeks.equals("KS003")){
            keterangan = "Konsumen biasa";        
        }else
                {
                    keterangan = "Tidak Terdaftar";
                }
        txtketerangan.setText(""+keterangan);
    }//GEN-LAST:event_cmkodekonsumenActionPerformed

    private void cmbkodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkodebarangActionPerformed
        // TODO add your handling code here:
        String kdbarang,namabarang,satuan;
        double hargabarang;
        
        kdbarang = String.valueOf(cmbkodebarang.getSelectedItem());
        
        if (kdbarang.equals("B001")){
            namabarang="Pena";
            hargabarang=10000;
            satuan = "pcs";
        }else
            if (kdbarang.equals("B002")){
            namabarang="Pensil";
            hargabarang=5500;
            satuan = "pack";
        }else
                if (kdbarang.equals("B003")){
                namabarang="Buku";
                hargabarang=15000;
                satuan = "Lusin";
        }else
                {
            namabarang="Penghapus";
            hargabarang=50000;
            satuan = "box";
        }
        txtnamabarang.setText(""+namabarang);
        txthargabarang.setText(""+hargabarang);
        txtsatuan.setText(""+satuan);
    }//GEN-LAST:event_cmbkodebarangActionPerformed

    private void txtjumlahbeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjumlahbeliActionPerformed
        // TODO add your handling code here:
        double jumlahbeli;
    }//GEN-LAST:event_txtjumlahbeliActionPerformed

    private void btnprosesdiskonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosesdiskonActionPerformed
        // TODO add your handling code here:
        double hargabarang, diskon;
        int jumlahbeli;
        
        jumlahbeli = Integer.parseInt(txtjumlahbeli.getText());
        hargabarang = Double.parseDouble(txthargabarang.getText());
        
        if (jumlahbeli > 10) {
            diskon = hargabarang * 0.1 ;
        }else
        {
            diskon = 0;
        }
        txtdiskon.setText(""+diskon);
    }//GEN-LAST:event_btnprosesdiskonActionPerformed

    private void btnprosestotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprosestotalActionPerformed
        // TODO add your handling code here:
        double hargabarang,diskon,totalbayar;
        int jumlahbeli;
        
        hargabarang = Double.parseDouble(txthargabarang.getText());
        jumlahbeli = Integer.parseInt(txtjumlahbeli.getText());
        diskon = Double.parseDouble(txtdiskon.getText());
        
        totalbayar = (hargabarang * jumlahbeli)-diskon;
        txttotal.setText(""+totalbayar);
        
    }//GEN-LAST:event_btnprosestotalActionPerformed

    private void btnuangbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuangbayarActionPerformed
        // TODO add your handling code here:
        double  totalbayar,uangbayar,uangkembalian;
        
        totalbayar = Double.parseDouble(txttotal.getText());
        uangbayar = Double.parseDouble(txtuangbayar.getText());
        
        if (uangbayar > totalbayar) {
            uangkembalian = uangbayar - totalbayar;
            txtuangkembalian.setText(""+uangkembalian);
        }else
        {
            txtuangkembalian.setText("Uang Anda Kurang");
        }
    }//GEN-LAST:event_btnuangbayarActionPerformed

    private void btnexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
        // TODO add your handling code here:
        txtnama1.setText("");
        txtketerangan.setText("");
        txtnamabarang.setText("");
        txtsatuan.setText("");
        txtjumlahbeli.setText("");
        txtdiskon.setText("");
        txthargabarang.setText("");
        txttotal.setText("");
        txtuangbayar.setText("");
        txtuangkembalian.setText("");
            cmbkodebarang.setSelectedItem(null);
            cmkodekonsumen.setSelectedItem(null);
            txtnama1.setText("");
    }//GEN-LAST:event_bthapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjekPenjualanSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjekPenjualanSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjekPenjualanSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjekPenjualanSederhana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjekPenjualanSederhana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bthapus;
    private javax.swing.JButton btnex;
    private javax.swing.JButton btnprosesdiskon;
    private javax.swing.JButton btnprosestotal;
    private javax.swing.JButton btnuangbayar;
    private javax.swing.JComboBox<String> cmbkodebarang;
    private javax.swing.JComboBox<String> cmkodekonsumen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtdiskon;
    private javax.swing.JTextField txthargabarang;
    private javax.swing.JTextField txtjumlahbeli;
    private javax.swing.JTextField txtketerangan;
    private javax.swing.JTextField txtnama1;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtsatuan;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtuangbayar;
    private javax.swing.JTextField txtuangkembalian;
    // End of variables declaration//GEN-END:variables
}
